name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 6
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, x86, ARM64]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: MSBuild of plugin dll
      working-directory: .\
      run: msbuild RestApiToText.sln /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /p:PlatformToolset="v142"

    - name: Archive artifacts for x64
      if: matrix.build_platform == 'x64' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
          name: plugin_dll_x64
          path: ${{ matrix.build_platform }}\${{ matrix.build_configuration }}\RestApiToText.dll

    - name: Archive artifacts for x86
      if: matrix.build_platform == 'x86' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
          name: plugin_dll_x86
          path: ${{ matrix.build_configuration }}\RestApiToText.dll

    - name: Archive artifacts for ARM64
      if: matrix.build_platform == 'ARM64' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
          name: plugin_dll_ARM64
          path: ${{ matrix.build_platform }}\${{ matrix.build_configuration }}\RestApiToText.dll

